version: '3.9'

services:
  auth:
    restart: always
    build: ./auth/
    ports:
      - '8071:8071'
    depends_on:
      - postgres
      - redis
  redis:
    image: redis
  postgres:
    image: postgres